// VSTGOD - God Of Oneshots — Core Library
// Auto-generated from C:\Users\USER\Documents\VSTGOD- God Of Oneshots\VSTGOD- God Of Oneshots

export const CORE_LIBRARY_ROOT = 'C:\\Users\\USER\\Documents\\Core Library';

// Alternative roots tried in order if the primary path fails. The preferred way
// to locate the library is the in-app "LOCATE LIBRARY" picker (File System Access
// API), which works regardless of where the user puts the folder; these absolute
// paths are only a best-effort fallback for the legacy JUCE file-reader bridge.
export const CORE_LIBRARY_ROOTS = [
  CORE_LIBRARY_ROOT,
  'C:\\Users\\USER\\Documents\\VSTGOD- God Of Oneshots\\VSTGOD- God Of Oneshots',
  'I:\\kits\\new kits\\2024-2025\\VSTGOD- God Of Oneshots\\VSTGOD- God Of Oneshots',
];

export interface CoreSample { name: string; file: string; }

export const CORE_LIBRARY: Record<string, CoreSample[]> = {
  Accents: [
    { name: '67', file: '67.ogg' },
    { name: 'Airlock', file: 'Airlock.ogg' },
    { name: 'Allawn', file: 'Allawn.ogg' },
    { name: 'Alto Flute Legato', file: 'Alto Flute Legato.ogg' },
    { name: 'BATTLE', file: 'BATTLE.ogg' },
    { name: 'Blurry Particles', file: 'Blurry Particles.ogg' },
    { name: 'Brooding Bass', file: 'Brooding Bass.ogg' },
    { name: 'Calling Seq', file: 'Calling Seq.nksn.ogg' },
    { name: 'Carousel', file: 'Carousel.ogg' },
    { name: 'Cello Trills & Trems', file: 'Cello Trills & Trems.ogg' },
    { name: 'Chords Staccatos', file: 'Chords Staccatos.ogg' },
    { name: 'Cliffhangers', file: 'Cliffhangers.ogg' },
    { name: 'Disturbing News', file: 'Disturbing News.ogg' },
    { name: 'Drift Pluck', file: 'Drift Pluck.ogg' },
    { name: 'Dry', file: 'Dry.ogg' },
    { name: 'Emotional Cello Shorts', file: 'Emotional Cello Shorts.ogg' },
    { name: 'Emotional Viola', file: 'Emotional Viola.ogg' },
    { name: 'Everlasting Electric', file: 'Everlasting Electric.ogg' },
    { name: 'Falls', file: 'Falls.ogg' },
    { name: 'Fancy Robot Party', file: 'Fancy Robot Party.ogg' },
    { name: 'Flutter', file: 'Flutter.ogg' },
    { name: 'Guitopia - Suspense', file: 'Guitopia - Suspense.ogg' },
    { name: 'Gushing codine', file: 'Gushing codine.ogg' },
    { name: 'High Strings Marcato', file: 'High Strings Marcato.nksn.ogg' },
    { name: 'High Strings Spiccato', file: 'High Strings Spiccato.ogg' },
    { name: 'High Strings Staccato', file: 'High Strings Staccato.ogg' },
    { name: 'Inbetween The Walls', file: 'Inbetween The Walls.ogg' },
    { name: 'Intimate Violin', file: 'Intimate Violin.ogg' },
    { name: 'Lead - Hit Felt Piano', file: 'Lead - Hit Felt Piano.ogg' },
    { name: 'Leaking Oxygen', file: 'Leaking Oxygen.ogg' },
    { name: 'Leaking Oxygen 2', file: 'Leaking Oxygen 2.ogg' },
    { name: 'Low Brass', file: 'Low Brass.ogg' },
    { name: 'Low Brass Staccato', file: 'Low Brass Staccato.ogg' },
    { name: "Mariner's Song", file: "Mariner's Song.ogg" },
    { name: 'Medieval Lute', file: 'Medieval Lute.ogg' },
    { name: 'Morin Khuur', file: 'Morin Khuur.ogg' },
    { name: 'Motion Through Devotion', file: 'Motion Through Devotion.ogg' },
    { name: 'Musicbox', file: 'Musicbox.ogg' },
    { name: 'Muted', file: 'Muted.ogg' },
    { name: 'Nature', file: 'Nature.ogg' },
    { name: 'Orchestral Harp', file: 'Orchestral Harp.ogg' },
    { name: 'phrygian', file: 'phrygian.ogg' },
    { name: 'Scattered', file: 'Scattered.ogg' },
    { name: 'Sheperds', file: 'Sheperds.ogg' },
    { name: 'Showtime', file: 'Showtime.ogg' },
    { name: 'Speed Chase', file: 'Speed Chase.ogg' },
    { name: 'Staccatissimo', file: 'Staccatissimo.ogg' },
    { name: 'Steel Revolution', file: 'Steel Revolution.ogg' },
    { name: 'TRP', file: 'TRP.ogg' },
    { name: 'Trumpets Muted Staccato', file: 'Trumpets Muted Staccato.ogg' },
  ],
  Analog: [
    { name: "70's Solo", file: "70's Solo.ogg" },
    { name: '80s Baby', file: '80s Baby.wav' },
    { name: 'Acid Blomp', file: 'Acid Blomp.ogg' },
    { name: 'Angelification', file: 'Angelification.ogg' },
    { name: 'Big Synthy', file: 'Big Synthy.ogg' },
    { name: 'BP Strings', file: 'BP Strings.ogg' },
    { name: 'Burn The House', file: 'Burn The House.ogg' },
    { name: 'Euro Noise', file: 'Euro Noise.ogg' },
    { name: 'Heavy Blaster', file: 'Heavy Blaster.ogg' },
    { name: 'Iapetus', file: 'Iapetus.ogg' },
    { name: 'Juno', file: 'Juno.wav' },
    { name: 'Main Techniques', file: 'Main Techniques.ogg' },
    { name: 'Muddied Up', file: 'Muddied Up.ogg' },
    { name: 'Napolean', file: 'Napolean.wav' },
    { name: 'NURS', file: 'NURS.ogg' },
    { name: 'Poly Scythe', file: 'Poly Scythe.ogg' },
    { name: 'Qulited', file: 'Qulited.wav' },
    { name: 'Short Pizzicato', file: 'Short Pizzicato.ogg' },
    { name: 'Space Jams', file: 'Space Jams.ogg' },
    { name: 'Space Organ', file: 'Space Organ.ogg' },
    { name: 'Speci', file: 'Speci.ogg' },
    { name: 'Stack', file: 'Stack.ogg' },
    { name: 'Stinger', file: 'Stinger.wav' },
    { name: 'Switzerland', file: 'Switzerland.ogg' },
    { name: 'Unikaraine', file: 'Unikaraine.ogg' },
    { name: 'Vocal Soup', file: 'Vocal Soup.ogg' },
  ],
  Bass: [
    { name: 'A Sine From Above', file: 'A Sine From Above.ogg' },
    { name: 'Bassic Grinder', file: 'Bassic Grinder.nksn.ogg' },
    { name: 'Detroit', file: 'Detroit.wav' },
    { name: 'Dope Man', file: 'Dope Man.wav' },
    { name: 'Fatal', file: 'Fatal.ogg' },
    { name: 'Game Bass', file: 'Game Bass.ogg' },
    { name: 'Grand', file: 'Grand.ogg' },
    { name: 'Heavy Bottom', file: 'Heavy Bottom.ogg' },
    { name: 'Low Brass', file: 'Low Brass.ogg' },
    { name: 'Mosaic Bass', file: 'Mosaic Bass.ogg' },
    { name: 'Reese Bass', file: 'Reese Bass.ogg' },
    { name: 'SYMPHONIC DEPTHS', file: 'SYMPHONIC DEPTHS.ogg' },
    { name: 'SYNTH HYBRID', file: 'SYNTH HYBRID.ogg' },
    { name: 'SYNTHETIC ORCHESTRA', file: 'SYNTHETIC ORCHESTRA.ogg' },
    { name: 'Screamy Mother', file: 'Screamy Mother.ogg' },
    { name: 'TIGHT SYNTHETIC', file: 'TIGHT SYNTHETIC.ogg' },
    { name: 'TRACTOR BEAM', file: 'TRACTOR BEAM.ogg' },
    { name: 'Tri Saw Sub', file: 'Tri Saw Sub.ogg' },
    { name: 'UNSETTLED', file: 'UNSETTLED.ogg' },
    { name: 'WILDFIRE', file: 'WILDFIRE.ogg' },
    { name: 'Way Down Deep', file: 'Way Down Deep.ogg' },
    { name: 'Wow', file: 'Wow.ogg' },
    { name: 'Yin And Yang', file: 'Yin And Yang.ogg' },
  ],
  Bell: [
    { name: 'Ball Game', file: 'Ball Game.ogg' },
    { name: 'Chatter Octaves', file: 'Chatter Octaves.ogg' },
    { name: 'Frost', file: 'Frost.ogg' },
    { name: 'Glimmer Of Nope', file: 'Glimmer Of Nope.ogg' },
    { name: 'Golden', file: 'Golden.ogg' },
    { name: 'Granulada', file: 'Granulada.ogg' },
    { name: 'Heavy Handed', file: 'Heavy Handed.ogg' },
    { name: 'Hedwig', file: 'Hedwig.ogg' },
    { name: 'Hour Glass', file: 'Hour Glass.ogg' },
    { name: 'Jelly', file: 'Jelly.ogg' },
    { name: 'Lofi', file: 'Lofi.ogg' },
    { name: 'Long', file: 'Long.ogg' },
    { name: 'Luz Del Sol Vibes', file: 'Luz Del Sol Vibes.ogg' },
    { name: 'Malleto', file: 'Malleto.ogg' },
    { name: 'Marimba Shimmer', file: 'Marimba Shimmer.ogg' },
    { name: 'Mirada', file: 'Mirada.ogg' },
    { name: 'Motor', file: 'Motor.ogg' },
    { name: 'Permafrost', file: 'Permafrost.ogg' },
    { name: 'Real', file: 'Real.ogg' },
    { name: 'Rremolo Bowed', file: 'Rremolo Bowed.ogg' },
    { name: 'Senza T Drum', file: 'Senza T Drum.ogg' },
    { name: 'Sola', file: 'Sola.ogg' },
    { name: 'Sous Marin', file: 'Sous Marin.ogg' },
    { name: 'Staccato', file: 'Staccato.ogg' },
    { name: 'Swirling Bells', file: 'Swirling Bells.ogg' },
    { name: 'Transistor Belly', file: 'Transistor Belly.ogg' },
    { name: 'Tremolo', file: 'Tremolo.ogg' },
    { name: 'Tremolo Fast', file: 'Tremolo Fast.ogg' },
    { name: 'Tronish Vibes', file: 'Tronish Vibes.ogg' },
    { name: 'Vintage', file: 'Vintage.ogg' },
  ],
  Ethnic: [
    { name: 'Bazouki', file: 'Bazouki.ogg' },
    { name: 'Bellows', file: 'Bellows.ogg' },
    { name: 'Big Money', file: 'Big Money.ogg' },
    { name: 'Blocarooey', file: 'Blocarooey.ogg' },
    { name: 'Celtic Harp', file: 'Celtic Harp.ogg' },
    { name: 'Ceremony', file: 'Ceremony.ogg' },
    { name: 'Deeper Tape', file: 'Deeper Tape.nksn.ogg' },
    { name: 'DreamMallets', file: 'DreamMallets.ogg' },
    { name: 'Duk Duk', file: 'Duk Duk.ogg' },
    { name: 'Gaohachet', file: 'Gaohachet.ogg' },
    { name: 'Kalimba', file: 'Kalimba.ogg' },
    { name: 'Main Techniques', file: 'Main Techniques.ogg' },
    { name: 'Nightshade', file: 'Nightshade.ogg' },
    { name: 'No Age', file: 'No Age.ogg' },
    { name: 'Prima Domra', file: 'Prima Domra.ogg' },
    { name: 'Su Gzheng', file: 'Su Gzheng.ogg' },
    { name: 'Swarm', file: 'Swarm.ogg' },
    { name: 'Sweetness', file: 'Sweetness.ogg' },
    { name: 'Tagelharpa', file: 'Tagelharpa.ogg' },
    { name: 'Weary Traveller', file: 'Weary Traveller.ogg' },
    { name: 'Welcome Home Rico', file: 'Welcome Home Rico.ogg' },
  ],
  FX: [
    { name: 'Arctic Terns', file: 'Arctic Terns.ogg' },
    { name: 'Audio Rate Entertainment', file: 'Audio Rate Entertainment.ogg' },
    { name: 'Bird Invasion', file: 'Bird Invasion.ogg' },
    { name: 'Boiling Anger', file: 'Boiling Anger.ogg' },
    { name: 'Candy', file: 'Candy.ogg' },
    { name: 'Car Crush', file: 'Car Crush.ogg' },
    { name: 'Coarse Echoes', file: 'Coarse Echoes.ogg' },
    { name: 'Crescendi', file: 'Crescendi.ogg' },
    { name: 'Distant Factory', file: 'Distant Factory.ogg' },
    { name: "Don't Worry Bout It", file: "Don't Worry Bout It.ogg" },
    { name: 'Easter Island', file: 'Easter Island.ogg' },
    { name: 'Furious Road', file: 'Furious Road.ogg' },
    { name: 'Gentle Cry', file: 'Gentle Cry.ogg' },
    { name: 'Ghostly', file: 'Ghostly.ogg' },
    { name: 'Manx Attack', file: 'Manx Attack.ogg' },
    { name: 'Mindhaunter', file: 'Mindhaunter.ogg' },
    { name: 'Mysterious Quarks', file: 'Mysterious Quarks.ogg' },
    { name: 'NoZ', file: 'NoZ.ogg' },
    { name: 'Noise 2 Meet U', file: 'Noise 2 Meet U.ogg' },
    { name: 'Penguin Acid', file: 'Penguin Acid.ogg' },
    { name: 'Reaper', file: 'Reaper.ogg' },
    { name: 'Rises', file: 'Rises.ogg' },
    { name: 'Scrape The Bone', file: 'Scrape The Bone.ogg' },
    { name: 'Scratching the Surface', file: 'Scratching the Surface.ogg' },
    { name: 'Slowdowns', file: 'Slowdowns.ogg' },
    { name: 'SpaceMuffin', file: 'SpaceMuffin.ogg' },
    { name: 'Sun', file: 'Sun.ogg' },
    { name: 'The End Game', file: 'The End Game.ogg' },
    { name: 'Tuned Ambience', file: 'Tuned Ambience.ogg' },
    { name: 'Up & Down', file: 'Up & Down.ogg' },
    { name: 'Vertigo', file: 'Vertigo.ogg' },
    { name: 'Vox Flux', file: 'Vox Flux.ogg' },
  ],
  Guitar: [
    { name: 'Aircraft', file: 'Aircraft.ogg' },
    { name: 'Alternative Ray', file: 'Alternative Ray.ogg' },
    { name: 'American Tape', file: 'American Tape.ogg' },
    { name: 'American Trem', file: 'American Trem.ogg' },
    { name: 'Angry Airwaves', file: 'Angry Airwaves.ogg' },
    { name: 'Arp Land', file: 'Arp Land.ogg' },
    { name: 'Celtic Castle', file: 'Celtic Castle.ogg' },
    { name: 'Classic Jazz Chorus', file: 'Classic Jazz Chorus.ogg' },
    { name: 'Falling Leaves', file: 'Falling Leaves.ogg' },
    { name: 'Fretty Krueger', file: 'Fretty Krueger.ogg' },
    { name: 'Fullerton', file: 'Fullerton.ogg' },
    { name: 'Funk Flight', file: 'Funk Flight.ogg' },
    { name: 'Funky Fare', file: 'Funky Fare.ogg' },
    { name: 'Growl', file: 'Growl.ogg' },
    { name: 'Guitar Euphoria', file: 'Guitar Euphoria.ogg' },
    { name: 'Harmonico', file: 'Harmonico.ogg' },
    { name: 'Hey You', file: 'Hey You.ogg' },
    { name: 'Hold and Reverse', file: 'Hold and Reverse.ogg' },
    { name: 'Humpback', file: 'Humpback.ogg' },
    { name: 'Indie Rock Guitar', file: 'Indie Rock Guitar.ogg' },
    { name: 'Jazzyone', file: 'Jazzyone.ogg' },
    { name: 'Live or Pool', file: 'Live or Pool.ogg' },
    { name: 'Mahayana', file: 'Mahayana.ogg' },
    { name: 'Mellow EDM', file: 'Mellow EDM.ogg' },
    { name: 'Mint Pop', file: 'Mint Pop.ogg' },
    { name: 'Motor', file: 'Motor.ogg' },
    { name: 'Neo Funk', file: 'Neo Funk.ogg' },
    { name: 'Night Ride', file: 'Night Ride.ogg' },
    { name: 'Pedal Combo', file: 'Pedal Combo.ogg' },
    { name: 'Pedal Combo 2', file: 'Pedal Combo 2.ogg' },
    { name: 'Plucked', file: 'Plucked.ogg' },
    { name: 'Post Rock Guitar', file: 'Post Rock Guitar.ogg' },
    { name: 'Renaxxance II', file: 'Renaxxance II.ogg' },
    { name: 'Soft Nylon Guitar', file: 'Soft Nylon Guitar.ogg' },
    { name: 'Soft Nylon Guitar 2', file: 'Soft Nylon Guitar 2.ogg' },
    { name: 'Space Mint', file: 'Space Mint.ogg' },
    { name: 'Suspicious', file: 'Suspicious.ogg' },
    { name: 'Sweet Slides', file: 'Sweet Slides.ogg' },
    { name: 'Synthar', file: 'Synthar.ogg' },
    { name: 'Tek Guitar', file: 'Tek Guitar.ogg' },
    { name: 'Through the Night', file: 'Through the Night.ogg' },
    { name: 'Tomorrow', file: 'Tomorrow.ogg' },
    { name: 'Tread Lightly', file: 'Tread Lightly.ogg' },
    { name: 'Tremolang', file: 'Tremolang.ogg' },
    { name: 'Underwater Skatepark', file: 'Underwater Skatepark.ogg' },
    { name: 'Veil Industries', file: 'Veil Industries.ogg' },
    { name: 'What Do I Know', file: 'What Do I Know.ogg' },
    { name: 'Wobbly Harmonics', file: 'Wobbly Harmonics.ogg' },
    { name: 'in it', file: 'in it.ogg' },
    { name: 'the 16th', file: 'the 16th.ogg' },
  ],
  Keys: [
    { name: '1960', file: '1960.ogg' },
    { name: '1968', file: '1968.ogg' },
    { name: '4ths', file: '4ths.ogg' },
    { name: 'Airplane Window Sunrise', file: 'Airplane Window Sunrise.ogg' },
    { name: 'Apathy Atrophied', file: 'Apathy Atrophied.ogg' },
    { name: 'Ariel', file: 'Ariel.ogg' },
    { name: 'Bedtime Story', file: 'Bedtime Story.ogg' },
    { name: 'Beloved', file: 'Beloved.ogg' },
    { name: 'Bouquet', file: 'Bouquet.ogg' },
    { name: 'Cinematic Mellow', file: 'Cinematic Mellow.ogg' },
    { name: 'Dark', file: 'Dark.ogg' },
    { name: 'Easy', file: 'Easy.ogg' },
    { name: 'Echo of the Abyss', file: 'Echo of the Abyss.ogg' },
    { name: 'Felt Piano', file: 'Felt Piano.ogg' },
    { name: 'Freaky Fair', file: 'Freaky Fair.ogg' },
    { name: 'Harrison', file: 'Harrison.ogg' },
    { name: 'Humble Beginnings', file: 'Humble Beginnings.ogg' },
    { name: 'Hybrid', file: 'Hybrid.ogg' },
    { name: 'Ignition Keys', file: 'Ignition Keys.ogg' },
    { name: 'Isolation', file: 'Isolation.ogg' },
    { name: 'KeyslnTime', file: 'KeyslnTime.ogg' },
    { name: 'Kimbre', file: 'Kimbre.ogg' },
    { name: 'Lettemin', file: 'Lettemin.ogg' },
    { name: 'MistyFM', file: 'MistyFM.ogg' },
    { name: 'Old Mcdonald', file: 'Old Mcdonald.ogg' },
    { name: 'PN Wind', file: 'PN Wind.ogg' },
    { name: 'PN Zebrano', file: 'PN Zebrano.ogg' },
    { name: 'Piano On Tape', file: 'Piano On Tape.ogg' },
    { name: 'Piano On Tape 5', file: 'Piano On Tape 5.ogg' },
    { name: 'Pulses', file: 'Pulses.ogg' },
    { name: 'Spacetrack', file: 'Spacetrack.ogg' },
    { name: 'Summer Rain', file: 'Summer Rain.ogg' },
    { name: 'Sway', file: 'Sway.ogg' },
    { name: 'THE FAMOUS', file: 'THE FAMOUS.ogg' },
    { name: 'The Return', file: 'The Return.ogg' },
    { name: 'Vibra', file: 'Vibra.ogg' },
    { name: 'Winter Taiga', file: 'Winter Taiga.ogg' },
    { name: 'Wonder', file: 'Wonder.ogg' },
  ],
  Leads: [
    { name: '2000', file: '2000.ogg' },
    { name: 'Angry Reso', file: 'Angry Reso.ogg' },
    { name: 'Anthem', file: 'Anthem.ogg' },
    { name: 'Aquamarine', file: 'Aquamarine.ogg' },
    { name: 'Fill It', file: 'Fill It.ogg' },
    { name: 'Good 1', file: 'Good 1.ogg' },
    { name: 'HP Lead', file: 'HP Lead.ogg' },
    { name: 'Junk FM', file: 'Junk FM.ogg' },
    { name: 'Mosaic', file: 'Mosaic.ogg' },
    { name: 'Old Games', file: 'Old Games.ogg' },
    { name: 'Play Weak', file: 'Play Weak.ogg' },
    { name: 'Rash', file: 'Rash.ogg' },
    { name: 'Saturation', file: 'Saturation.ogg' },
    { name: 'Speak Up', file: 'Speak Up.ogg' },
    { name: 'Underground', file: 'Underground.ogg' },
  ],
  Modulated: [
    { name: '3D Bell', file: '3D Bell.ogg' },
    { name: 'Almost Not There', file: 'Almost Not There.ogg' },
    { name: 'Analog Popcorn Pluck', file: 'Analog Popcorn Pluck.ogg' },
    { name: 'Animated Flute', file: 'Animated Flute.ogg' },
    { name: 'Ascending Gemini', file: 'Ascending Gemini.ogg' },
    { name: 'Bee Sting', file: 'Bee Sting.ogg' },
    { name: 'Broken Tape', file: 'Broken Tape.ogg' },
    { name: 'Buzz Bye', file: 'Buzz Bye.ogg' },
    { name: 'Chukchi', file: 'Chukchi.ogg' },
    { name: 'Circuit Bent Bells', file: 'Circuit Bent Bells.ogg' },
    { name: 'Cyber Tokyo', file: 'Cyber Tokyo.ogg' },
    { name: 'Disintegration', file: 'Disintegration.ogg' },
    { name: 'Down and Back and Forth', file: 'Down and Back and Forth.ogg' },
    { name: 'Emo Pulse', file: 'Emo Pulse.ogg' },
    { name: 'Enchanting Bells', file: 'Enchanting Bells.ogg' },
    { name: 'Expansion', file: 'Expansion.ogg' },
    { name: 'Forever Pluck', file: 'Forever Pluck.ogg' },
    { name: 'Formant Motion', file: 'Formant Motion.ogg' },
    { name: 'Friendship', file: 'Friendship.ogg' },
    { name: 'Fuzzy Signal', file: 'Fuzzy Signal.ogg' },
    { name: 'Galatea', file: 'Galatea.ogg' },
    { name: 'Getaway Pluck', file: 'Getaway Pluck.ogg' },
    { name: 'Hydraulic Oscillation', file: 'Hydraulic Oscillation.ogg' },
    { name: 'In Charge', file: 'In Charge.ogg' },
    { name: 'Infinity Attack', file: 'Infinity Attack.ogg' },
    { name: "It's All Rushing Back", file: "It_s All Rushing Back.ogg" },
    { name: 'Lost Sunset', file: 'Lost Sunset.ogg' },
    { name: 'Lost Sunset Part 1', file: 'Lost Sunset - Part_1.ogg' },
    { name: 'Lost in Space', file: 'Lost in Space.ogg' },
    { name: 'Missed Call', file: 'Missed Call.ogg' },
    { name: 'My Only Reflection', file: 'My Only Relflection.ogg' },
    { name: 'Mysticist', file: 'Mysticist.ogg' },
    { name: 'Night Glider Ride', file: 'Night Glider Ride.ogg' },
    { name: 'Nothing Into Everything', file: 'Nothing Into Everything.ogg' },
    { name: 'OREN AMBARCHI - Cloud Drop', file: 'OREN AMBARCHI - Cloud Drop.ogg' },
    { name: 'OREN AMBARCHI - Glitch Cloud II', file: 'OREN AMBARCHI - Glitch Cloud II.ogg' },
    { name: 'Qlwx - Major Keyssss', file: 'Qlwx -  Major Keyssss.ogg' },
    { name: 'Qlwx - Smokers Room', file: 'Qlwx - Smokers Room.ogg' },
    { name: 'R2D2', file: 'R2D2.ogg' },
    { name: 'Saturn', file: 'Saturn.ogg' },
    { name: 'Short Fizzer', file: 'Short Fizzer.ogg' },
    { name: 'Slot Machine', file: 'Slot Machine.ogg' },
    { name: 'Summer Pluck', file: 'Summer Pluck.ogg' },
    { name: 'Surgery', file: 'Surgery.ogg' },
    { name: 'Triplicator', file: 'Triplicator.ogg' },
    { name: 'Tripulsing', file: 'Tripulsing.ogg' },
    { name: 'Vibraphone Pulse', file: 'Vibraphone Pulse.ogg' },
    { name: 'WAVE', file: 'WAVE.ogg' },
    { name: 'Wavey', file: 'Wavey.ogg' },
    { name: 'Worker Bee', file: 'Worker Bee.ogg' },
  ],
  Organ: [
    { name: '3 Sling TI', file: '3 Sling TI.ogg' },
    { name: 'Bee Trees', file: 'Bee Trees.ogg' },
    { name: 'Celestial Organs', file: 'Celestial Organs.ogg' },
    { name: 'Chopped Up Organs', file: 'Chopped Up Organs.ogg' },
    { name: 'Disca Queen', file: 'Disca Queen.ogg' },
    { name: 'Drunk in Church', file: 'Drunk in Church.ogg' },
    { name: 'DxJx Organ', file: 'DxJx Organ.ogg' },
    { name: 'HoreGaine', file: 'HoreGaine.ogg' },
    { name: 'KEY Organ 1', file: 'KEY Organ 1.ogg' },
    { name: 'KEY Organ 2', file: 'KEY Organ 2.ogg' },
    { name: 'Organik', file: 'Organik.ogg' },
    { name: 'Orions', file: 'Orions.ogg' },
    { name: 'Picky Lead', file: 'Picky Lead.ogg' },
    { name: 'Rhodes Sling', file: 'Rhodes Sling.ogg' },
    { name: 'Sandman Dream', file: 'Sandman Dream.ogg' },
    { name: 'Stolen Moments', file: 'Stolen Moments.ogg' },
    { name: 'Velour', file: 'Velour.ogg' },
  ],
  Pads: [
    { name: 'Aeolian Whispers', file: 'Aeolian Whispers.ogg' },
    { name: 'Androids Dream', file: 'Androids Dream.ogg' },
    { name: 'Angle Grinder', file: 'Angle Grinder.ogg' },
    { name: 'Beyond The Wall', file: 'Beyond The Wall.ogg' },
    { name: 'Bright Daze', file: 'Bright Daze.ogg' },
    { name: 'Broken Circuits', file: 'Broken Circuits.ogg' },
    { name: 'Compfluter', file: 'Compfluter.ogg' },
    { name: 'Conifer Pine', file: 'Conifer Pine.ogg' },
    { name: 'Crystal Earth', file: 'Crystal Earth.ogg' },
    { name: 'Death Knell', file: 'Death Knell.ogg' },
    { name: 'Deep Space', file: 'Deep Space.ogg' },
    { name: 'Dew Drops', file: 'Dew Drops.ogg' },
    { name: 'Distant Factory', file: 'Distant Factory.ogg' },
    { name: 'Dont Let Go', file: 'Dont Let Go.ogg' },
    { name: 'Dwarven Ruins', file: 'Dwarven Ruins.ogg' },
    { name: 'Early Birds', file: 'Early Birds.ogg' },
    { name: 'Favorite Color Tan', file: 'Favorite Color Tan.ogg' },
    { name: 'Flow State', file: 'Flow State.ogg' },
    { name: 'Gentle Shores', file: 'Gentle Shores.ogg' },
    { name: 'Glory Days', file: 'Glory Days.ogg' },
    { name: 'Granular Glaciers', file: 'Granular Glaciers.ogg' },
    { name: 'Insert Coin', file: 'Insert Coin.ogg' },
    { name: 'Jackrabbit', file: 'Jackrabbit.ogg' },
    { name: 'Jupiters Tears', file: 'Jupiters Tears.ogg' },
    { name: 'Laser Whips', file: 'Laser Whips.ogg' },
    { name: 'Lava Flow', file: 'Lava Flow.ogg' },
    { name: 'Mercury', file: 'Mercury.ogg' },
    { name: 'Mountain Springs', file: 'Mountain Springs.ogg' },
    { name: 'Ocean Eyes', file: 'Ocean Eyes.ogg' },
    { name: 'Pick Up Your Phone', file: 'Pick Up Your Phone.ogg' },
    { name: 'Pulsar', file: 'Pulsar.ogg' },
    { name: 'Racing', file: 'Racing.ogg' },
    { name: 'Rebellion Hope Pad', file: 'Rebellion Hope Pad.ogg' },
    { name: 'Resonant Fleet Pad', file: 'Resonant Fleet Pad.ogg' },
    { name: 'Retro Ghosts', file: 'Retro Ghosts.ogg' },
    { name: 'SEM Goodness', file: 'SEM Goodness.ogg' },
    { name: 'Shimmering Mirage', file: 'Shimmering Mirage.ogg' },
    { name: 'Slight Buzz', file: 'Slight Buzz.ogg' },
    { name: 'Smoking Flue', file: 'Smoking Flue.ogg' },
    { name: 'Smooth Reflections', file: 'Smooth Reflections.ogg' },
    { name: 'Snowfall Pad', file: 'Snowfall Pad.ogg' },
    { name: 'Space Whale Pad', file: 'Space Whale Pad.ogg' },
    { name: 'Speaking In Tongues', file: 'Speaking In Tongues.ogg' },
    { name: 'Speed Limit', file: 'Speed Limit.ogg' },
    { name: 'Stumble', file: 'Stumble.ogg' },
    { name: 'Sunset Pad', file: 'Sunset Pad.ogg' },
    { name: 'Suprise', file: 'Suprise.ogg' },
    { name: 'Swoop Pad', file: 'Swoop Pad.ogg' },
    { name: 'The Dead Rise', file: 'The Dead Rise.ogg' },
    { name: 'The Force Pad', file: 'The Force Pad.ogg' },
    { name: 'The Mariana Trench', file: 'The Mariana Trench.ogg' },
    { name: 'The Mummy', file: 'The Mummy.ogg' },
    { name: 'This Came From Pluto', file: 'This Came From Pluto.ogg' },
    { name: 'Uncertain Space', file: 'Uncertain Space.ogg' },
    { name: 'Underwater', file: 'Underwater.ogg' },
    { name: 'Unwritten Bio', file: 'Unwritten Bio.ogg' },
    { name: 'Valley Sunrise', file: 'Valley Sunrise.ogg' },
    { name: 'Watery Pad', file: 'Watery Pad.ogg' },
    { name: 'Yellow Warbler', file: 'Yellow Warbler.ogg' },
  ],
  Pluck: [
    { name: 'Aggressive Kats', file: 'Aggressive Kats.ogg' },
    { name: 'Barry Is Back', file: 'Barry Is Back.ogg' },
    { name: 'Bedtime Stories', file: 'Bedtime Stories.ogg' },
    { name: 'Big Hair Energy', file: 'Big Hair Energy.ogg' },
    { name: 'Bread Hammond', file: 'Bread Hammond.ogg' },
    { name: 'Brown Bag Vibes', file: 'Brown Bag Vibes.ogg' },
    { name: 'Callous Tips', file: 'Callous Tips.ogg' },
    { name: 'Chuckster', file: 'Chuckster.ogg' },
    { name: 'Collection Plate', file: 'Collection Plate.ogg' },
    { name: 'Cotton Mouth Keys', file: 'Cotton Mouth Keys.ogg' },
    { name: 'Dennis Roadman', file: 'Dennis Roadman.ogg' },
    { name: 'Dirty Danza', file: 'Dirty Danza..ogg' },
    { name: 'Distant Winds', file: 'Distant Winds.ogg' },
    { name: 'Dreamy Axxe', file: 'Dreamy Axxe.ogg' },
    { name: 'Eclipsed Passion', file: 'Eclipsed Passion.ogg' },
    { name: 'Faulter Reed', file: 'Faulter Reed.ogg' },
    { name: 'Faux Bando', file: 'Faux Bando.ogg' },
    { name: 'Fluffy Frets', file: 'Fluffy Frets.ogg' },
    { name: 'Free Lovin', file: 'Free Lovin.ogg' },
    { name: 'Funkees', file: 'Funkees.ogg' },
    { name: 'Girls Night Out', file: 'Girls Night Out.ogg' },
    { name: 'Give Em Butterflies', file: 'Give Em Butterflies.ogg' },
    { name: 'Glass Road', file: 'Glass Road.ogg' },
    { name: 'Greasy Keys', file: 'Greasy Keys.ogg' },
    { name: 'Gucci Piano', file: 'Gucci Piano.ogg' },
    { name: 'Jah Roam', file: 'Jah Roam.ogg' },
    { name: 'Keep It Toro', file: 'Keep It Toro.ogg' },
    { name: 'Liquid Lover', file: 'Liquid Lover.ogg' },
    { name: 'Make A Wish', file: 'Make A Wish.ogg' },
    { name: 'Molded Roads', file: 'Molded Roads.ogg' },
    { name: "Oh It's Be Eight", file: "Oh It's Be Eight.ogg" },
    { name: 'PL Ring My Bell', file: 'PL Ring My Bell.ogg' },
    { name: 'PL Squarehack', file: 'PL Squarehack.ogg' },
    { name: 'PL Voxtrot', file: 'PL Voxtrot.ogg' },
    { name: 'Press Pads', file: 'Press Pads.ogg' },
    { name: 'Prohibition Grand', file: 'Prohibition Grand.ogg' },
    { name: 'Quadro Suave', file: 'Quadro Suave.ogg' },
    { name: 'Rain Brows Lite', file: 'Rain Brows Lite.ogg' },
    { name: 'Reel Flack', file: 'Reel Flack.ogg' },
    { name: 'Ribbon Clav', file: 'Ribbon Clav.ogg' },
    { name: 'Ring Keys', file: 'Ring Keys.ogg' },
    { name: 'Rodgers Entrance', file: 'Rodgers Entrance.ogg' },
    { name: 'Roundabout', file: 'Roundabout.ogg' },
    { name: 'Sauce Neck', file: 'Sauce Neck.ogg' },
    { name: 'Seaside Views', file: 'Seaside Views.ogg' },
    { name: 'Sheeno Bee', file: 'Sheeno Bee.ogg' },
    { name: 'Shortcut Keys', file: 'Shortcut Keys.ogg' },
    { name: 'Sky Ribbon Reel', file: 'Sky Ribbon Reel.ogg' },
    { name: 'Slammed Upright', file: 'Slammed Upright.ogg' },
    { name: 'Smokey Drips', file: 'Smokey Drips.ogg' },
  ],
  'Real Brass': [
    { name: 'Bankroll', file: 'Bankroll.ogg' },
    { name: 'Brass Lead', file: 'Brass Lead.ogg' },
    { name: 'Brass Mid', file: 'Brass Mid.ogg' },
    { name: 'Brass Section', file: 'Brass Section.ogg' },
    { name: 'Breathiness', file: 'Breathiness.ogg' },
    { name: 'Commas', file: 'Commas.ogg' },
    { name: 'Countdown', file: 'Countdown.ogg' },
    { name: 'Degraded Bone', file: 'Degraded Bone.ogg' },
    { name: 'Detached', file: 'Detached.ogg' },
    { name: 'Europa', file: 'Europa.ogg' },
    { name: 'Fluttertongue', file: 'Fluttertongue.ogg' },
    { name: 'French Horns Muted Sustain', file: 'French Horns Muted Sustain.ogg' },
    { name: 'French Horns Sustain', file: 'French Horns Sustain.ogg' },
    { name: 'Horns a3', file: 'Horns a3.ogg' },
    { name: 'Horns a3 Marcato Short', file: 'Horns a3 Marcato Short.ogg' },
    { name: 'Horns a3 Staccato', file: 'Horns a3 Staccato.ogg' },
    { name: 'Horns a3 Swell Long', file: 'Horns a3 Swell Long.ogg' },
    { name: 'Horns a3 Swell Short', file: 'Horns a3 Swell Short.ogg' },
    { name: 'Horns a4 - Legato', file: 'Horns a4 - Legato.ogg' },
    { name: 'Krusty Krew Anthem', file: 'Krusty Krew Anthem.ogg' },
    { name: 'Legato WIP', file: 'Legato WIP.ogg' },
    { name: 'Low Brass Marcato', file: 'Low Brass Marcato.ogg' },
    { name: 'Low Brass Shards Grid', file: 'Low Brass Shards Grid.ogg' },
    { name: 'Low Brass Sustain', file: 'Low Brass Sustain.ogg' },
    { name: 'Momentum Grid', file: 'Momentum Grid.ogg' },
    { name: 'Morin Khuur', file: 'Morin Khuur.ogg' },
    { name: 'Multitongue', file: 'Multitongue.ogg' },
    { name: 'Short Sfz', file: 'Short Sfz.ogg' },
    { name: 'Short Staccatissimo', file: 'Short Staccatissimo.ogg' },
    { name: 'Time Machine', file: 'Time Machine.ogg' },
    { name: 'Trumpet Solo - Legato', file: 'Trumpet Solo - Legato.ogg' },
    { name: 'Trumpet Solo - Long', file: 'Trumpet Solo - Long.ogg' },
    { name: 'Trumpet Solo - Long Flutter', file: 'Trumpet Solo - Long Flutter.ogg' },
    { name: 'Trumpet Solo - Rip', file: 'Trumpet Solo - Rip.ogg' },
    { name: 'Trumpets a4 Marcato Short', file: 'Trumpets a4 Marcato Short.ogg' },
    { name: 'Trumpets a4 Staccatissimo', file: 'Trumpets a4 Staccatissimo.ogg' },
    { name: 'Tuba', file: 'Tuba.ogg' },
    { name: 'Woods', file: 'Woods.ogg' },
    { name: 'a3 Marcato Short', file: 'a3 Marcato Short.ogg' },
    { name: 'a3 Staccato', file: 'a3 Staccato.ogg' },
  ],
  Strings: [
    { name: '1st Violins', file: '1st Violins.ogg' },
    { name: '1st Violins - Pizzicato', file: '1st Violins - Pizzicato.ogg' },
    { name: 'Antelope', file: 'Antelope.ogg' },
    { name: 'Antimatter Strings', file: 'Antimatter Strings.nksn.ogg' },
    { name: 'Armed & Dangerous', file: 'Armed & Dangerous.ogg' },
    { name: 'B Time machine', file: 'B Time machine.ogg' },
    { name: 'Bartok Pizzicato', file: 'Bartok Pizzicato.ogg' },
    { name: 'Bladerunner Strings', file: 'Bladerunner Strings.ogg' },
    { name: 'Bright Big Sky', file: 'Bright Big Sky.ogg' },
    { name: 'Celesta Mutation', file: 'Celesta Mutation.ogg' },
    { name: 'Celli Grid - Time Madness', file: 'Celli Grid - Time Madness.ogg' },
    { name: 'Celli Shards Grid', file: 'Celli Shards Grid.ogg' },
    { name: 'D Time Machine', file: 'D Time Machine.ogg' },
    { name: "Deckard's Strings", file: "Deckard's Strings.ogg" },
    { name: 'Duplets', file: 'Duplets.ogg' },
    { name: 'Economic', file: 'Economic.ogg' },
    { name: 'Eightve', file: 'Eightve.ogg' },
    { name: 'Energetic Shorts', file: 'Energetic Shorts.ogg' },
    { name: 'Ensemble', file: 'Ensemble.ogg' },
    { name: 'Ensemble of Strings', file: 'Ensemble of Strings.ogg' },
    { name: 'Epic', file: 'Epic.ogg' },
    { name: 'Guarneri Violin', file: 'Guarneri Violin.ogg' },
    { name: 'Guarneri Violin Shorts', file: 'Guarneri Violin Shorts.ogg' },
    { name: 'High Spiccato Blurred', file: 'High Spiccato Blurred.ogg' },
    { name: 'Intimate Strings', file: 'Intimate Strings.ogg' },
    { name: "Lush70'sFade", file: "Lush70'sFade.ogg" },
    { name: 'MW - Stutter', file: 'MW - Stutter.ogg' },
    { name: 'Marcato', file: 'Marcato.ogg' },
    { name: 'Miami Skyline', file: 'Miami Skyline.ogg' },
    { name: 'Moded', file: 'Moded.ogg' },
    { name: 'Money longer', file: 'Money longer.ogg' },
    { name: 'Movie', file: 'Movie.ogg' },
    { name: 'Ostinatum (Spic)', file: 'Ostinatum (Spic).ogg' },
    { name: 'Pulsing Momentum', file: 'Pulsing Momentum.ogg' },
    { name: 'Quartet', file: 'Quartet.ogg' },
    { name: 'Short Octave', file: 'Short Octave.ogg' },
    { name: 'Spiccato', file: 'Spiccato.ogg' },
    { name: 'Strings High', file: 'Strings High.ogg' },
    { name: 'Sunrise Comet', file: 'Sunrise Comet.ogg' },
    { name: 'The Real', file: 'The Real.ogg' },
    { name: 'Time machine', file: 'Time machine.ogg' },
    { name: 'Too Many Nights', file: 'Too Many Nights.ogg' },
    { name: 'Tremolo', file: 'Tremolo.ogg' },
    { name: 'Umbriel', file: 'Umbriel.ogg' },
    { name: 'Verso Swell', file: 'Verso Swell.ogg' },
    { name: 'Violins Tone', file: 'Violins Tone.ogg' },
    { name: 'Warm Cinematic Strings', file: 'Warm Cinematic Strings.ogg' },
    { name: 'Woods High - Short', file: 'Woods High - Short.ogg' },
    { name: 'Yayli', file: 'Yayli.ogg' },
    { name: 'lush string', file: 'lush string.ogg' },
  ],
  Synth: [
    { name: 'A False Future', file: 'A False Future.ogg' },
    { name: 'After The Storm', file: 'After The Storm.ogg' },
    { name: 'Akwar', file: 'Akwar.ogg' },
    { name: 'Allarms', file: 'Allarms.ogg' },
    { name: 'Au Revoir', file: 'Au Revoir.ogg' },
    { name: 'Azimuth', file: 'Azimuth.ogg' },
    { name: 'Before Sunset', file: 'Before Sunset.ogg' },
    { name: 'Black Butterfly', file: 'Black Butterfly.ogg' },
    { name: 'Bronze Bomber', file: 'Bronze Bomber.ogg' },
    { name: 'Counting Stars', file: 'Counting Stars.ogg' },
    { name: 'Dew Drops', file: 'Dew Drops.ogg' },
    { name: 'Dirty Shakin', file: 'Dirty Shakin.ogg' },
    { name: 'Dope or Dopey', file: 'Dope or Dopey.ogg' },
    { name: 'Fatigue', file: 'Fatigue.ogg' },
    { name: 'Finjo', file: 'Finjo.ogg' },
    { name: 'Fire Inside', file: 'Fire Inside.ogg' },
    { name: 'Fragile Feedback', file: 'Fragile Feedback.ogg' },
    { name: 'Glisten', file: 'Glisten.ogg' },
    { name: 'Going into Orbit', file: 'Going into Orbit.ogg' },
    { name: 'Hard Choice', file: 'Hard Choice.ogg' },
    { name: 'Hoover 1', file: 'Hoover 1.ogg' },
    { name: 'In Contrast', file: 'In Contrast.ogg' },
    { name: "Knife's Edge", file: "Knife's Edge.ogg" },
    { name: 'Leader', file: 'Leader.ogg' },
    { name: 'Love Synth', file: 'Love Synth.ogg' },
    { name: 'Matra', file: 'Matra.ogg' },
    { name: 'Mouth Accordion', file: 'Mouth Accordion.ogg' },
    { name: 'Musical Telemetry', file: 'Musical Telemetry.ogg' },
    { name: 'Neverending', file: 'Neverending.ogg' },
    { name: 'Old String Synth', file: 'Old String Synth.ogg' },
    { name: 'Pacmon', file: 'Pacmon.ogg' },
    { name: 'Ringing Synth', file: 'Ringing Synth.ogg' },
    { name: 'SY Tragic Kingdom', file: 'SY Tragic Kingdom.ogg' },
    { name: 'SY Tribal Dance', file: 'SY Tribal Dance.ogg' },
    { name: 'Sau', file: 'Sau.ogg' },
    { name: 'Sauce Alert', file: 'Sauce Alert.ogg' },
    { name: 'She Came At Night To Feed On The Weak', file: 'She Came At Night To Feed On The Weak.ogg' },
    { name: 'Spoke up', file: 'Spoke up.ogg' },
    { name: 'Staticocity Cinematica', file: 'Staticocity Cinematica.ogg' },
    { name: 'Synth Braams', file: 'Synth Braams.ogg' },
    { name: 'Talking Synth', file: 'Talking Synth.ogg' },
    { name: 'The Takers', file: 'The Takers.ogg' },
    { name: 'Thrasher', file: 'Thrasher.ogg' },
    { name: 'ULTRON LEAD', file: 'ULTRON LEAD.ogg' },
    { name: 'Uneasy Approach', file: 'Uneasy Approach.ogg' },
    { name: 'Warning', file: 'Warning.ogg' },
    { name: 'Wooden Saw', file: 'Wooden Saw.ogg' },
  ],
  'Synth Brass': [
    { name: 'Brass', file: 'Brass.ogg' },
    { name: 'Janus', file: 'Janus.ogg' },
    { name: 'Long Octaves', file: 'Long Octaves.ogg' },
    { name: 'Long Pulses', file: 'Long Pulses.ogg' },
    { name: 'Mimas', file: 'Mimas.ogg' },
    { name: 'Oberon', file: 'Oberon.ogg' },
    { name: 'Short Staccatissimo', file: 'Short Staccatissimo.ogg' },
    { name: 'a4 Marcato Short', file: 'a4 Marcato Short.ogg' },
    { name: 'a4 Staccato', file: 'a4 Staccato.ogg' },
    { name: 'a4 Sustains', file: 'a4 Sustains.ogg' },
  ],
  Texture: [
    { name: 'ASMR', file: 'ASMR.ogg' },
    { name: 'ATMOS', file: 'ATMOS.ogg' },
    { name: 'Atmosphere', file: 'Atmosphere.ogg' },
    { name: 'Campfire', file: 'Campfire.ogg' },
    { name: 'DKVPZ', file: 'DKVPZ.ogg' },
    { name: 'Favorite Texture', file: 'Favorite Texture.ogg' },
    { name: 'Ice dropping', file: 'Ice dropping.ogg' },
    { name: 'JUNGLE', file: 'JUNGLE.ogg' },
    { name: 'Ocean Floor', file: 'Ocean Floor.ogg' },
    { name: 'Palos', file: 'Palos.ogg' },
    { name: 'RESTREAT', file: 'RESTREAT.ogg' },
    { name: 'RIOT', file: 'RIOT.ogg' },
    { name: 'Redman', file: 'Redman.ogg' },
    { name: 'Reels', file: 'Reels.ogg' },
    { name: 'Terrifying Night', file: 'Terrifying Night.ogg' },
    { name: 'Voltage Venom', file: 'Voltage Venom.ogg' },
    { name: 'helix texture', file: 'helix texture.ogg' },
    { name: 'rule', file: 'rule.ogg' },
    { name: 'texture - chimes', file: 'texture - chimes.ogg' },
    { name: 'worried', file: 'worried.ogg' },
  ],
  Vox: [
    { name: 'Ah Ee Oo', file: 'Ah Ee Oo.ogg' },
    { name: 'Bend Ha Up', file: 'Bend Ha Up.ogg' },
    { name: 'Bending The Suspense', file: 'Bending The Suspense.ogg' },
    { name: 'Bring it back', file: 'Bring it back.ogg' },
    { name: 'casper', file: 'casper.ogg' },
    { name: 'dhummm', file: 'dhummm.ogg' },
    { name: 'Fly High LoFi', file: 'Fly High LoFi.nksn.ogg' },
    { name: 'Godspeed', file: 'Godspeed.ogg' },
    { name: 'Haunted House', file: 'Haunted House.ogg' },
    { name: 'Hey There', file: 'Hey There.ogg' },
    { name: 'Hoowayyy', file: 'Hoowayyy.ogg' },
    { name: 'Just Breath', file: 'Just Breath.ogg' },
    { name: 'Long Natural Oh', file: 'Long Natural Oh.ogg' },
    { name: 'Mf think he a cow', file: 'Mf think he a cow.ogg' },
    { name: 'Motor', file: 'Motor.ogg' },
    { name: 'Mrph', file: 'Mrph.ogg' },
    { name: 'Oohhh shiiiii', file: 'Oohhh shiiiii.ogg' },
    { name: 'Phrases', file: 'Phrases.ogg' },
    { name: 'Plavalaguna', file: 'Plavalaguna.ogg' },
    { name: 'Scribble', file: 'Scribble.ogg' },
    { name: 'Shift Beauty', file: 'Shift Beauty.ogg' },
    { name: 'Shorts', file: 'Shorts.ogg' },
    { name: 'Soul Choirs', file: 'Soul Choirs.ogg' },
    { name: 'Strept', file: 'Strept.ogg' },
    { name: 'Super Ahh Femalwe', file: 'Super Ahh Femalwe.ogg' },
    { name: 'Swell EhAh', file: 'Swell EhAh.ogg' },
    { name: 'The Awakening', file: 'The Awakening.nksn.ogg' },
    { name: 'Unda Da Sea', file: 'Unda Da Sea.ogg' },
    { name: 'Under The Radar', file: 'Under The Radar.ogg' },
    { name: 'yhhhayyy', file: 'yhhhayyy.ogg' },
  ],
  Wind: [
    { name: 'Alto Flute', file: 'Alto Flute.ogg' },
    { name: 'Bop', file: 'Bop.ogg' },
    { name: 'Ethnic Flute', file: 'Ethnic Flute.ogg' },
    { name: 'Flute Fix', file: 'Flute Fix.ogg' },
    { name: 'Fukumean', file: 'Fukumean.ogg' },
    { name: 'LoFi Flute', file: 'LoFi Flute.ogg' },
    { name: 'Lust', file: 'Lust.ogg' },
    { name: 'Mellow Flutes', file: 'Mellow Flutes.ogg' },
    { name: 'Mountain Origins', file: 'Mountain Origins.ogg' },
    { name: 'Praise The Lord', file: 'Praise The Lord.ogg' },
    { name: 'Real Flute', file: 'Real Flute.ogg' },
    { name: 'Short Marcato', file: 'Short Marcato.ogg' },
    { name: 'Short Staccatissimo', file: 'Short Staccatissimo.ogg' },
    { name: 'Short Staccato', file: 'Short Staccato.ogg' },
    { name: 'SoftFlutes', file: 'SoftFlutes.ogg' },
    { name: 'Time machine', file: 'Time machine.ogg' },
    { name: 'Vibes Flute', file: 'Vibes Flute.ogg' },
    { name: 'Waterwheel', file: 'Waterwheel.ogg' },
    { name: 'Whistle', file: 'Whistle.ogg' },
    { name: 'Woodwind Quartet', file: 'Woodwind Quartet.ogg' },
    { name: 'X - Flute', file: 'X - Flute.ogg' },
    { name: 'YOSEMITE', file: 'YOSEMITE.ogg' },
    { name: 'Yale', file: 'Yale.ogg' },
    { name: 'flutter', file: 'flutter.ogg' },
    { name: 'walzy', file: 'walzy.ogg' },
  ],
};
