import React, { useState, useEffect, useMemo, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, Book, Sparkles, Zap, Play, Plus, Info, Filter, LayoutGrid, ScrollText } from 'lucide-react';
import { AkashicManifest, AkashicSample } from '@/services/types';
import { SpectralAura } from './SpectralAura';

interface HallOfRecordsProps {
  engineRef: React.MutableRefObject<any>;
  activePad: number;
  onLoadSample?: (sample: AkashicSample) => void;
}

export const HallOfRecords: React.FC<HallOfRecordsProps> = ({
  engineRef,
  activePad,
  onLoadSample
}) => {
  const [manifest, setManifest] = useState<AkashicManifest | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [hoveredSample, setHoveredSample] = useState<AkashicSample | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Load the genuine Akashic records generated by the DSP Indexer
    fetch('/akashic_manifest.json')
      .then(res => res.json())
      .then(data => {
        const akashicSamples: AkashicSample[] = [];
        Object.entries(data.categories).forEach(([cat, samples]: [string, any]) => {
          samples.forEach((s: any) => {
            akashicSamples.push({
              id: s.id,
              name: s.name,
              path: s.path,
              category: cat,
              semanticTags: s.semanticTags || [],
              acoustic: {
                energy: s.acousticProfile?.energy || 50,
                spectralCentroid: s.acousticProfile?.peakFrequency || 1000,
                decayTime: s.acousticProfile?.decayTime || 0.5,
                fundamentalFreq: s.acousticProfile?.fundamentalFreq || 0,
              },
              relatedIds: s.relationships || []
            });
          });
        });

        setManifest({
          name: data.name || "The Akashic Archive",
          version: data.version || "2.0.0",
          lastIndexed: new Date().toISOString(),
          samples: akashicSamples,
          categories: Object.keys(data.categories).reduce((acc, cat) => ({
            ...acc,
            [cat]: { description: `Divine ${cat} collection`, icon: 'book', sampleCount: data.categories[cat].length }
          }), {})
        });
      })
      .catch(err => console.error("Archive failure:", err));
  }, []);

  const filteredSamples = useMemo(() => {
    if (!manifest) return [];
    return manifest.samples.filter(s => {
      const matchesSearch = s.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
                           s.semanticTags.some(t => t.includes(searchQuery.toLowerCase()));
      const matchesCat = !selectedCategory || s.category === selectedCategory;
      return matchesSearch && matchesCat;
    });
  }, [manifest, searchQuery, selectedCategory]);

  const samplesByShelf = useMemo(() => {
    const shelves: Record<string, AkashicSample[]> = {};
    filteredSamples.forEach(s => {
      if (!shelves[s.category]) shelves[s.category] = [];
      shelves[s.category].push(s);
    });
    return shelves;
  }, [filteredSamples]);

  const handleAudition = (sample: AkashicSample) => {
    if (engineRef.current) {
      engineRef.current.previewSample(sample.path);
    }
  };

  const handleLoad = (sample: AkashicSample) => {
    if (engineRef.current) {
      engineRef.current.loadSampleByPath(sample.path, activePad);
      onLoadSample?.(sample);
    }
  };

  return (
    <div className="flex flex-col h-full bg-[#080504] text-[#f8ddd2] overflow-hidden relative">
      {/* Search Header */}
      <div className="p-8 pb-4 flex items-center justify-between z-20">
        <div className="flex flex-col">
          <h2 className="text-2xl font-black uppercase tracking-[0.4em] bg-gradient-to-r from-white to-[#c29623] bg-clip-text text-fill-transparent opacity-80">
            Hall of Records
          </h2>
          <span className="text-[10px] font-bold text-[#c29623]/60 uppercase tracking-[0.2em] mt-2 flex items-center gap-2">
            <Sparkles size={12} /> Akashic Indexer V2.0 Active
          </span>
        </div>

        <div className="relative w-96">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#c29623]/40" size={18} />
          <input 
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search the Divine Memory..."
            className="w-full bg-[#1a0a05]/60 border border-[#c29623]/20 rounded-full py-3 pl-12 pr-6 text-sm focus:outline-none focus:border-[#ff6600]/40 transition-all placeholder:text-[#c29623]/20"
          />
        </div>
      </div>

      {/* Main Archive Area */}
      <div 
        ref={scrollRef}
        className="flex-1 overflow-y-auto px-8 py-4 custom-scrollbar vg-hall-of-records"
      >
        <AnimatePresence mode="popLayout">
          {Object.entries(samplesByShelf).map(([category, samples], shelfIdx) => (
            <motion.div 
              key={category}
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: shelfIdx * 0.1 }}
              className="relative"
            >
              <div className="flex items-center gap-4 mb-4">
                <div className="w-8 h-[1px] bg-gradient-to-r from-transparent to-[#c29623]/40" />
                <h3 className="text-xs font-black uppercase tracking-[0.3em] text-[#c29623]/60">{category}</h3>
                <div className="flex-1 h-[1px] bg-gradient-to-r from-[#c29623]/40 to-transparent" />
              </div>

              <div className="vg-library-shelf">
                <div className="vg-shelf-glow" />
                {samples.map((sample, idx) => (
                  <motion.div
                    key={sample.id}
                    className="vg-tome"
                    style={{ height: `${100 + (sample.acoustic.energy * 0.6)}px` }}
                    onMouseEnter={() => {
                      setHoveredSample(sample);
                      handleAudition(sample);
                    }}
                    onMouseLeave={() => setHoveredSample(null)}
                    onClick={() => handleLoad(sample)}
                  >
                    <div className="vg-tome-spine">
                      {sample.name}
                    </div>
                    
                    <div className="vg-tome-content">
                      <div className="vg-runes">𐎟𐏂𐎠𐎥</div>
                      <div className="text-[10px] font-black uppercase tracking-tighter mb-1 truncate">
                        {sample.name}
                      </div>
                      <div className="flex gap-1 flex-wrap mb-4">
                        {sample.semanticTags.slice(0, 2).map(tag => (
                          <span key={tag} className="text-[7px] border border-white/10 px-1 rounded-sm opacity-40">
                            {tag}
                          </span>
                        ))}
                      </div>

                      <div className="vg-tome-aura relative overflow-hidden">
                         <SpectralAura 
                            energy={sample.acoustic.energy}
                            decayTime={sample.acoustic.decayTime}
                            spectralCentroid={sample.acoustic.spectralCentroid}
                         />
                      </div>

                      <button className="mt-auto py-1 bg-[#ff6600] text-black text-[8px] font-black uppercase rounded shadow-[0_0_10px_rgba(255,102,0,0.4)]">
                        Recall to Pad {activePad + 1}
                      </button>
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          ))}
        </AnimatePresence>

        {filteredSamples.length === 0 && (
          <div className="flex flex-col items-center justify-center py-40 text-[#c29623]/20">
            <Book size={64} strokeWidth={1} />
            <span className="text-xs font-black uppercase tracking-[0.5em] mt-8">The archives are silent</span>
          </div>
        )}
      </div>

      {/* Floating Insight Panel */}
      <AnimatePresence>
        {hoveredSample && (
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            className="absolute bottom-10 right-10 w-64 glass-panel p-6 border-[#c29623]/20 z-50 pointer-events-none"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 rounded bg-[#ff6600]/10 text-[#ff6600]">
                <ScrollText size={16} />
              </div>
              <div className="flex flex-col">
                <span className="text-[10px] font-black uppercase tracking-widest text-white/40">Sonic Insight</span>
                <span className="text-xs font-bold">{hoveredSample.name}</span>
              </div>
            </div>

            <div className="space-y-3">
              <div className="flex justify-between items-end">
                <span className="text-[9px] uppercase tracking-widest opacity-40">Resonance</span>
                <span className="text-[10px] font-mono text-[#ff6600]">
                  {Math.round(hoveredSample.acoustic.energy)}%
                </span>
              </div>
              <div className="h-1 bg-white/5 rounded-full overflow-hidden">
                <motion.div 
                  initial={{ width: 0 }}
                  animate={{ width: `${hoveredSample.acoustic.energy}%` }}
                  className="h-full bg-gradient-to-r from-[#ff6600] to-[#c29623]" 
                />
              </div>

              <div className="flex justify-between items-end">
                <span className="text-[9px] uppercase tracking-widest opacity-40">Decay</span>
                <span className="text-[10px] font-mono text-[#c29623]">
                  {hoveredSample.acoustic.decayTime.toFixed(2)}s
                </span>
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-white/5">
              <p className="text-[9px] italic opacity-40 leading-relaxed">
                "An ancient artifact recovered from the {hoveredSample.category} dimension. Its vibrations carry the weight of forgotten ages."
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
