/**
 * FAQTimerSection.tsx — Premium Countdown Timer & FAQ Accordion
 *
 * Implements a gold/ember themed rolling 24-hour pre-order countdown timer
 * and a fully interactive, accessible FAQ accordion using Framer Motion
 * for smooth visual animations.
 */

import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence, useInView } from 'framer-motion';
import { HelpCircle, Timer, AlertCircle, ChevronDown, Check, Sparkles } from 'lucide-react';
import PreOrderModal from './PreOrderModal';

// Theme Colors
const COLORS = {
  void: 'hsl(240, 30%, 4%)',
  obsidian: 'hsl(0, 0%, 4%)',
  goldHex: '#c29623',
  goldLight: '#e8c547',
  goldDark: '#8c6613',
  emberHex: '#ff6600',
  emberLight: '#ff8533',
  ether: 'rgba(255,255,255,0.05)',
  textPrimary: '#ffffff',
  textSecondary: 'rgba(255,255,255,0.65)',
  textDim: 'rgba(255,255,255,0.35)',
};

const GOLD_EMBER_GRADIENT = `linear-gradient(135deg, ${COLORS.goldHex} 0%, ${COLORS.goldLight} 50%, ${COLORS.emberHex} 100%)`;
const GLOW_RADIAL = `radial-gradient(circle, rgba(194, 150, 35, 0.08) 0%, rgba(255, 102, 0, 0.03) 50%, transparent 100%)`;

interface FAQItem {
  question: string;
  answer: string;
}

const FAQ_ITEMS: FAQItem[] = [
  {
    question: 'Is the license lifetime?',
    answer: 'Yes, your license is a lifetime license. It includes all future v1.x updates, bug fixes, and feature additions in the version 1 cycle with no annual fees or subscriptions.',
  },
  {
    question: 'How many machines can I activate?',
    answer: 'You can activate VST GOD on up to 2 active machines (macOS and/or Windows) simultaneously with a single license key. You can easily deactivate machines in your user portal to transfer licenses.',
  },
  {
    question: 'How do I link my purchase?',
    answer: 'Go to the user portal and register an account using the exact same email address you used at checkout. Your purchase and license key will be automatically linked to your account.',
  },
  {
    question: 'Can I use this in commercial projects?',
    answer: 'Yes, 100%. All sound presets, waveforms, and audio outputs generated by VST GOD are completely royalty-free and can be used in your commercial music productions, films, games, and media projects.',
  },
];

// Helper Component: Individual Digit Slider for Countdown Transitions
function CountdownDigit({ value }: { value: string }) {
  return (
    <div
      style={{
        position: 'relative',
        height: '1.2em',
        width: '0.65em',
        display: 'inline-flex',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
      }}
    >
      <AnimatePresence mode="popLayout">
        <motion.span
          key={value}
          initial={{ y: '60%', opacity: 0 }}
          animate={{ y: '0%', opacity: 1 }}
          exit={{ y: '-60%', opacity: 0 }}
          transition={{ duration: 0.28, ease: [0.16, 1, 0.3, 1] }}
          style={{
            position: 'absolute',
            display: 'inline-block',
            lineHeight: 1,
          }}
        >
          {value}
        </motion.span>
      </AnimatePresence>
    </div>
  );
}

// Helper Component: Countdown Unit (Box + Label)
function CountdownUnit({ value, label }: { value: number; label: string }) {
  const padValue = value.toString().padStart(2, '0');
  
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, flex: 1 }}>
      <div
        style={{
          display: 'flex',
          background: 'rgba(15, 15, 20, 0.6)',
          border: '1px solid rgba(194, 150, 35, 0.15)',
          boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4), inset 0 0 12px rgba(194, 150, 35, 0.05)',
          borderRadius: 12,
          padding: '16px 8px',
          gap: 1,
          fontFamily: "'JetBrains Mono', monospace",
          fontSize: 'clamp(1.5rem, 4.5vw, 2.5rem)',
          fontWeight: 800,
          color: COLORS.goldLight,
          textShadow: '0 0 12px rgba(232, 197, 71, 0.2)',
          overflow: 'hidden',
          width: '100%',
          maxWidth: 90,
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <CountdownDigit value={padValue[0]} />
        <CountdownDigit value={padValue[1]} />
      </div>
      <span
        style={{
          fontSize: 'clamp(0.6rem, 1.2vw, 0.7rem)',
          fontWeight: 700,
          letterSpacing: '0.15em',
          textTransform: 'uppercase',
          color: COLORS.textDim,
          marginTop: 2,
        }}
      >
        {label}
      </span>
    </div>
  );
}

export default function FAQTimerSection() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);
  const [timeLeft, setTimeLeft] = useState({ days: 0, hours: 0, minutes: 0, seconds: 0 });
  const [progressPercent, setProgressPercent] = useState(100);

  const containerRef = useRef<HTMLElement>(null);
  const isInView = useInView(containerRef, { once: true, amount: 0.15 });

  // Handle the persistent rolling 24-hour cycle timer
  useEffect(() => {
    const getTargetTime = () => {
      if (typeof window === 'undefined') return Date.now() + 24 * 60 * 60 * 1000;
      const STORAGE_KEY = 'vst_god_preorder_expiry';
      const stored = localStorage.getItem(STORAGE_KEY);
      const now = Date.now();

      if (stored) {
        const expiry = parseInt(stored, 10);
        if (expiry > now) {
          return expiry;
        }
      }

      // If no stored value or expired, start a fresh 24h cycle
      const newExpiry = now + 24 * 60 * 60 * 1000;
      localStorage.setItem(STORAGE_KEY, newExpiry.toString());
      return newExpiry;
    };

    const targetTime = getTargetTime();

    const updateTimer = () => {
      const now = Date.now();
      let difference = targetTime - now;

      if (difference <= 0) {
        // Rolling cycle rollover
        const newExpiry = now + 24 * 60 * 60 * 1000;
        if (typeof window !== 'undefined') {
          localStorage.setItem('vst_god_preorder_expiry', newExpiry.toString());
        }
        difference = newExpiry - now;
      }

      // Calculate units
      const d = Math.floor(difference / (1000 * 60 * 60 * 24));
      const h = Math.floor((difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      const m = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
      const s = Math.floor((difference % (1000 * 60)) / 1000);

      setTimeLeft({ days: d, hours: h, minutes: m, seconds: s });

      // Progress bar percentage (out of a 24h window)
      const totalSecondsLeft = (d * 24 * 3600) + (h * 3600) + (m * 60) + s;
      const pct = (totalSecondsLeft / (24 * 3600)) * 100;
      setProgressPercent(pct);
    };

    updateTimer();
    const intervalId = setInterval(updateTimer, 1000);

    return () => clearInterval(intervalId);
  }, []);

  return (
    <section
      ref={containerRef}
      id="faq-timer"
      style={{
        padding: '120px clamp(20px, 5vw, 80px)',
        background: COLORS.void,
        position: 'relative',
        overflow: 'hidden',
        borderTop: `1px solid ${COLORS.ether}`,
        borderBottom: `1px solid ${COLORS.ether}`,
        fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
      }}
    >
      {/* Background Glow */}
      <div
        aria-hidden="true"
        style={{
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
          width: 800,
          height: 600,
          borderRadius: '50%',
          background: GLOW_RADIAL,
          pointerEvents: 'none',
          zIndex: 0,
        }}
      />

      <div style={{ maxWidth: 1100, margin: '0 auto', position: 'relative', zIndex: 1 }}>
        {/* Header Block */}
        <div style={{ textAlign: 'center', marginBottom: 64 }}>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8 }}
          >
            <div
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 8,
                padding: '6px 14px',
                borderRadius: 20,
                background: 'rgba(194, 150, 35, 0.08)',
                border: `1px solid ${COLORS.goldHex}33`,
                marginBottom: 16,
              }}
            >
              <Sparkles size={13} color={COLORS.goldLight} />
              <span
                style={{
                  fontSize: 11,
                  fontWeight: 700,
                  color: COLORS.goldLight,
                  letterSpacing: '0.12em',
                  textTransform: 'uppercase',
                }}
              >
                Divine Covenant
              </span>
            </div>

            <h2
              style={{
                fontSize: 'clamp(28px, 4.5vw, 48px)',
                fontWeight: 900,
                color: '#fff',
                margin: '0 0 16px',
                letterSpacing: '-0.02em',
                lineHeight: 1.15,
              }}
            >
              Temporal Urgency & FAQs
            </h2>
            <p
              style={{
                fontSize: 'clamp(14px, 1.8vw, 16px)',
                color: COLORS.textSecondary,
                maxWidth: 600,
                margin: '0 auto',
                lineHeight: 1.6,
              }}
            >
              Ensure you capture the early-bird pre-order pricing. Read our sacred alchemical directives below for clear guidelines.
            </p>
          </motion.div>
        </div>

        {/* Responsive Grid */}
        <div className="faq-timer-grid">
          {/* Left Column: Countdown Pre-order Card */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.2 }}
            style={{
              background: 'linear-gradient(135deg, rgba(15,15,20,0.8) 0%, rgba(8,8,10,0.85) 100%)',
              backdropFilter: 'blur(20px)',
              WebkitBackdropFilter: 'blur(20px)',
              border: `1px solid ${COLORS.goldHex}25`,
              borderRadius: 24,
              padding: 'clamp(24px, 5vw, 44px)',
              boxShadow: '0 24px 64px rgba(0, 0, 0, 0.6), inset 0 0 32px rgba(194, 150, 35, 0.02)',
              position: 'relative',
              display: 'flex',
              flexDirection: 'column',
              gap: 28,
            }}
          >
            {/* Top Amber Accent Line */}
            <div
              style={{
                position: 'absolute',
                top: 0,
                left: '15%',
                width: '70%',
                height: 1,
                background: `linear-gradient(90deg, transparent, ${COLORS.goldLight}, ${COLORS.emberHex}, transparent)`,
              }}
            />

            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: COLORS.emberLight, marginBottom: 8 }}>
                <Timer size={18} />
                <span style={{ fontSize: 13, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase' }}>
                  Early-Bird Offer Ending
                </span>
              </div>
              <h3 style={{ fontSize: 22, fontWeight: 800, color: '#fff', margin: 0, letterSpacing: '-0.01em' }}>
                Sacred Price Hold: $199
              </h3>
            </div>

            {/* Timer Grid */}
            <div style={{ display: 'flex', gap: 10, justifyContent: 'space-between', width: '100%' }}>
              <CountdownUnit value={timeLeft.days} label="Days" />
              <CountdownUnit value={timeLeft.hours} label="Hours" />
              <CountdownUnit value={timeLeft.minutes} label="Mins" />
              <CountdownUnit value={timeLeft.seconds} label="Secs" />
            </div>

            {/* Custom Animated Progress Bar */}
            <div style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: 8 }}>
              <div
                style={{
                  height: 6,
                  width: '100%',
                  background: 'rgba(255,255,255,0.03)',
                  borderRadius: 10,
                  overflow: 'hidden',
                  position: 'relative',
                }}
              >
                <motion.div
                  initial={{ width: '100%' }}
                  animate={{ width: `${progressPercent}%` }}
                  transition={{ duration: 0.5, ease: 'easeOut' }}
                  style={{
                    height: '100%',
                    borderRadius: 10,
                    background: `linear-gradient(90deg, ${COLORS.goldDark}, ${COLORS.goldLight}, ${COLORS.emberHex})`,
                    boxShadow: '0 0 10px rgba(232, 197, 71, 0.4)',
                  }}
                />
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, color: COLORS.textDim, fontWeight: 500 }}>
                <span>ROLLING 24H RESET CYCLE</span>
                <span>URGENT ASCENSION LOCK</span>
              </div>
            </div>

            {/* Price Details */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderTop: `1px solid ${COLORS.ether}`, paddingTop: 20 }}>
              <div>
                <span style={{ fontSize: 12, color: COLORS.textDim, textTransform: 'uppercase', letterSpacing: '0.05em', display: 'block', marginBottom: 2 }}>
                  STANDARD VALUATION
                </span>
                <span style={{ fontSize: 20, color: COLORS.textSecondary, textDecoration: 'line-through', fontWeight: 600 }}>
                  $299.00 USD
                </span>
              </div>
              <div style={{ textAlign: 'right' }}>
                <span style={{ fontSize: 12, color: COLORS.goldLight, fontWeight: 700, letterSpacing: '0.05em', display: 'block', marginBottom: 2 }}>
                  PRE-ORDER SPECIAL
                </span>
                <span style={{ fontSize: 32, color: '#fff', fontWeight: 900, textShadow: '0 0 16px rgba(255,255,255,0.1)' }}>
                  $199.00
                </span>
              </div>
            </div>

            {/* CTA Trigger */}
            <button
              onClick={() => setIsModalOpen(true)}
              style={{
                width: '100%',
                padding: '16px 24px',
                background: GOLD_EMBER_GRADIENT,
                border: 'none',
                borderRadius: 12,
                color: '#000',
                fontSize: 15,
                fontWeight: 800,
                letterSpacing: '0.04em',
                cursor: 'pointer',
                boxShadow: `0 8px 24px rgba(255, 102, 0, 0.15)`,
                transition: 'transform 0.25s, box-shadow 0.25s',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.transform = 'translateY(-2px)';
                e.currentTarget.style.boxShadow = `0 12px 32px rgba(255, 102, 0, 0.3)`;
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = 'translateY(0)';
                e.currentTarget.style.boxShadow = `0 8px 24px rgba(255, 102, 0, 0.15)`;
              }}
            >
              CLAIM $199 LICENSE NOW
            </button>

            {/* Trust disclaimer */}
            <div style={{ display: 'flex', gap: 8, alignItems: 'center', justifyContent: 'center', color: COLORS.textDim, fontSize: 12 }}>
              <AlertCircle size={14} color={COLORS.goldLight} style={{ flexShrink: 0 }} />
              <span>Early bird access includes all future v1.x expansions.</span>
            </div>
          </motion.div>

          {/* Right Column: FAQ Accordion */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.3 }}
            style={{ display: 'flex', flexDirection: 'column', gap: 16 }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, color: COLORS.goldLight, marginBottom: 8 }}>
              <HelpCircle size={20} />
              <h3 style={{ fontSize: 20, fontWeight: 800, color: '#fff', margin: 0 }}>
                Frequently Asked Revelations
              </h3>
            </div>

            {/* Accordion List */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {FAQ_ITEMS.map((item, index) => {
                const isOpen = expandedIndex === index;
                return (
                  <div
                    key={index}
                    style={{
                      background: 'rgba(255, 255, 255, 0.01)',
                      border: `1px solid ${isOpen ? COLORS.goldHex + '33' : COLORS.ether}`,
                      borderRadius: 16,
                      overflow: 'hidden',
                      transition: 'border-color 0.3s ease, background-color 0.3s ease',
                      boxShadow: isOpen ? '0 4px 24px rgba(0, 0, 0, 0.2)' : 'none',
                    }}
                  >
                    {/* Header Trigger */}
                    <button
                      id={`faq-title-${index}`}
                      aria-expanded={isOpen}
                      aria-controls={`faq-content-${index}`}
                      onClick={() => setExpandedIndex(isOpen ? null : index)}
                      style={{
                        width: '100%',
                        padding: '20px 24px',
                        background: 'transparent',
                        border: 'none',
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        textAlign: 'left',
                        cursor: 'pointer',
                        color: isOpen ? '#fff' : COLORS.textSecondary,
                        transition: 'color 0.2s ease',
                      }}
                      onMouseEnter={(e) => {
                        if (!isOpen) e.currentTarget.style.color = '#fff';
                      }}
                      onMouseLeave={(e) => {
                        if (!isOpen) e.currentTarget.style.color = COLORS.textSecondary;
                      }}
                    >
                      <span style={{ fontSize: 16, fontWeight: 700, paddingRight: 16 }}>
                        {item.question}
                      </span>
                      <motion.div
                        animate={{ rotate: isOpen ? 180 : 0 }}
                        transition={{ duration: 0.2, ease: 'easeInOut' }}
                        style={{ display: 'flex', color: isOpen ? COLORS.goldLight : COLORS.textDim }}
                      >
                        <ChevronDown size={18} />
                      </motion.div>
                    </button>

                    {/* Expandable Panel */}
                    <motion.div
                      id={`faq-content-${index}`}
                      role="region"
                      aria-labelledby={`faq-title-${index}`}
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: isOpen ? 'auto' : 0, opacity: isOpen ? 1 : 0 }}
                      transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
                      style={{ overflow: 'hidden' }}
                    >
                      <div
                        style={{
                          padding: '0 24px 20px',
                          color: COLORS.textSecondary,
                          fontSize: 14,
                          lineHeight: 1.6,
                          borderLeft: `3px solid ${COLORS.goldHex}`,
                          marginLeft: 24,
                          marginBottom: 4,
                          display: 'flex',
                          gap: 12,
                          alignItems: 'flex-start',
                        }}
                      >
                        <Check size={16} color={COLORS.goldLight} style={{ flexShrink: 0, marginTop: 3 }} />
                        <span>{item.answer}</span>
                      </div>
                    </motion.div>
                  </div>
                );
              })}
            </div>
          </motion.div>
        </div>
      </div>

      {/* Global CSS for Grid Responsiveness */}
      <style>{`
        .faq-timer-grid {
          display: grid;
          grid-template-columns: 1fr 1.2fr;
          gap: 48px;
          align-items: flex-start;
        }
        @media (max-width: 968px) {
          .faq-timer-grid {
            grid-template-columns: 1fr;
            gap: 56px;
          }
        }
      `}</style>

      {/* Checkout Modal */}
      <PreOrderModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        price={199}
      />
    </section>
  );
}
